import PDFDocument from 'pdfkit';

interface Risk {
  title?: string;
  issue?: string;
  description: string;
  severity: number;
  category?: string;
  regulation?: string;
  potentialFine?: string;
  fix?: string;
}

interface Fix {
  title: string;
  description: string;
  priority?: string;
  timeframe?: string;
}

interface Analysis {
  summary: string;
  overallRiskScore: number;
  risks: Risk[];
  fixes?: Fix[];
  policyUpdates?: any[];
  actionPlan?: any;
  positiveFindings?: string[];
  potentialFines?: string;
}

interface BrandingOptions {
  companyName?: string;
  logoUrl?: string;
  primaryColor?: string;
}

interface PDFOptions {
  companyName?: string;
  reportTitle?: string;
  includeBoilerplate?: boolean;
  branding?: BrandingOptions;
}

function getSeverityLabel(score: number): string {
  if (score >= 9) return 'critical';
  if (score >= 7) return 'high';
  if (score >= 5) return 'medium';
  return 'low';
}

const LEGAL_BOILERPLATE = `This compliance analysis report is generated by LifeØS AI for informational purposes only. 
This report does not constitute legal advice and should not be relied upon as such. 
Always consult with qualified legal counsel before making decisions related to regulatory compliance.
LifeØS and its affiliates are not responsible for any fines, penalties, or other consequences 
resulting from actions taken or not taken based on this report.`;

/**
 * Generate a PDF report from compliance analysis
 */
export async function generateCompliancePDF(
  analysis: Analysis,
  options: PDFOptions = {}
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: options.reportTitle || 'LifeØS Compliance Report',
          Author: 'LifeØS AI Compliance',
          Creator: 'LifeØS',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Use branding colors if provided
      const brandColor = options.branding?.primaryColor || '#0071e3';
      const brandName = options.branding?.companyName || options.companyName || 'LifeØS';

      // Colors
      const colors: Record<string, string> = {
        primary: brandColor,
        dark: '#1d1d1f',
        text: '#1d1d1f',
        muted: '#86868b',
        critical: '#ff3b30',
        high: '#ff9500',
        medium: '#ffcc00',
        low: '#34c759',
      };

      // Header with custom branding
      doc.rect(0, 0, doc.page.width, 100).fill(colors.dark);
      
      // Company Name (branded)
      doc.fillColor('#ffffff')
        .fontSize(24)
        .font('Helvetica-Bold')
        .text(brandName, 50, 35);
      
      // Subtitle
      doc.fontSize(12)
        .font('Helvetica')
        .fillColor('#ffffff')
        .text('Compliance Analysis Report', 50, 65);
      
      // Generated date
      doc.fillColor('#999999')
        .fontSize(9)
        .text(`Generated: ${new Date().toLocaleDateString('en-US', { 
          year: 'numeric', 
          month: 'long', 
          day: 'numeric'
        })}`, doc.page.width - 180, 40);

      // "Powered by LifeØS" if using custom branding
      if (options.branding?.companyName && options.branding.companyName !== 'LifeØS') {
        doc.fillColor('#666666')
          .fontSize(8)
          .text('Powered by LifeØS', doc.page.width - 180, 55);
      }

      // Risk Score Badge
      const score = analysis.overallRiskScore || 0;
      const scoreColor = score >= 8 ? colors.critical :
                         score >= 6 ? colors.high :
                         score >= 4 ? colors.medium : colors.low;

      doc.rect(doc.page.width - 100, 60, 50, 30).fill(scoreColor);
      doc.fillColor('#ffffff')
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(score.toFixed(1), doc.page.width - 95, 68);

      doc.moveDown(3);

      // Executive Summary
      doc.fillColor(colors.text)
        .fontSize(16)
        .font('Helvetica-Bold')
        .text('Executive Summary', 50, 130);
      doc.moveDown(0.5);
      doc.fillColor(colors.muted)
        .fontSize(10)
        .font('Helvetica')
        .text(analysis.summary || 'No summary available.', 50, doc.y, { width: doc.page.width - 100 });

      // Risk Overview
      doc.moveDown(2);
      doc.fillColor(colors.text)
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('Risk Overview', 50);
      doc.moveDown(0.5);

      // Risk cards
      const risks = analysis.risks || [];
      if (risks.length === 0) {
        doc.fillColor(colors.muted)
          .fontSize(10)
          .font('Helvetica')
          .text('No risks identified.', 50);
      } else {
        risks.forEach((risk, index) => {
          if (doc.y > doc.page.height - 150) doc.addPage();
          
          const severityColor = colors[getSeverityLabel(risk.severity)] || colors.medium;
          const riskTitle = risk.title || risk.issue || `Risk ${index + 1}`;
          
          doc.rect(50, doc.y, 5, 60).fill(severityColor);
          doc.fillColor(colors.text)
            .fontSize(11)
            .font('Helvetica-Bold')
            .text(`${index + 1}. ${riskTitle}`, 65, doc.y + 5);
          doc.fillColor(colors.muted)
            .fontSize(9)
            .font('Helvetica')
            .text(risk.description || '', 65, doc.y, { width: doc.page.width - 130 });
          
          if (risk.regulation || risk.potentialFine) {
            doc.text(`Regulation: ${risk.regulation || 'N/A'} | Potential Fine: ${risk.potentialFine || 'N/A'}`, 65, doc.y, {
              width: doc.page.width - 130,
            });
          }
          
          // Fix recommendation if available
          if (risk.fix) {
            doc.fillColor(brandColor)
              .fontSize(9)
              .font('Helvetica-Bold')
              .text('Recommended Fix:', 65, doc.y + 5);
            doc.fillColor(colors.text)
              .font('Helvetica')
              .text(risk.fix, 65, doc.y, { width: doc.page.width - 130 });
          }
          
          doc.moveDown(1.5);
        });
      }

      // Action Plan
      if (analysis.actionPlan) {
        if (doc.y > doc.page.height - 200) doc.addPage();
        doc.moveDown(1);
        doc.fillColor(colors.text)
          .fontSize(14)
          .font('Helvetica-Bold')
          .text('Action Plan', 50);
        doc.moveDown(0.5);

        // Handle both array and object action plan formats
        if (Array.isArray(analysis.actionPlan)) {
          analysis.actionPlan.forEach((day: any) => {
            if (doc.y > doc.page.height - 100) doc.addPage();
            doc.fillColor(brandColor)
              .fontSize(10)
              .font('Helvetica-Bold')
              .text(`Day ${day.day}: ${day.title || ''}`, 50);
            if (Array.isArray(day.tasks)) {
              day.tasks.forEach((task: string) => {
                doc.fillColor(colors.muted)
                  .fontSize(9)
                  .font('Helvetica')
                  .text(`• ${task}`, 60);
              });
            }
            doc.moveDown(0.5);
          });
        } else if (typeof analysis.actionPlan === 'object') {
          Object.entries(analysis.actionPlan).forEach(([key, value]) => {
            if (doc.y > doc.page.height - 100) doc.addPage();
            const dayLabel = key.replace(/_/g, '-').replace(/day/i, 'Day ');
            doc.fillColor(brandColor)
              .fontSize(10)
              .font('Helvetica-Bold')
              .text(dayLabel, 50);
            doc.fillColor(colors.muted)
              .fontSize(9)
              .font('Helvetica')
              .text(`• ${value}`, 60);
            doc.moveDown(0.5);
          });
        }
      }

      // Positive Findings (if available)
      if (analysis.positiveFindings && analysis.positiveFindings.length > 0) {
        if (doc.y > doc.page.height - 150) doc.addPage();
        doc.moveDown(1);
        doc.fillColor(colors.low)
          .fontSize(14)
          .font('Helvetica-Bold')
          .text('Positive Findings', 50);
        doc.moveDown(0.5);
        
        analysis.positiveFindings.forEach((finding) => {
          doc.fillColor(colors.muted)
            .fontSize(9)
            .font('Helvetica')
            .text(`✓ ${finding}`, 50);
        });
      }

      // Legal Disclaimer
      if (options.includeBoilerplate !== false) {
        doc.addPage();
        doc.fillColor(colors.muted)
          .fontSize(8)
          .font('Helvetica-Bold')
          .text('LEGAL DISCLAIMER', 50);
        doc.moveDown(0.5);
        doc.font('Helvetica')
          .text(LEGAL_BOILERPLATE, 50, doc.y, { 
            width: doc.page.width - 100,
            align: 'justify'
          });
      }

      // Footer with branding on all pages
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc.fillColor(colors.muted)
          .fontSize(8)
          .text(
            `${brandName} Compliance Report • Page ${i + 1} of ${pageCount}`,
            50,
            doc.page.height - 40,
            { align: 'center', width: doc.page.width - 100 }
          );
      }

      doc.end();
    } catch (error) {
      console.error('PDF generation error:', error);
      reject(error);
    }
  });
}

export { getSeverityLabel };
